// En İyi 100 editöryal temel listesi (bkz. kullanıcı isteği) — sıra/oy/puan burada KÜRETE
// EDİLMİŞ içerik olarak elle güncellenir (gerçek kullanıcı puanları bunun ÜZERİNE eklenir, bkz.
// src/routes/top100.js#blendRating). isim/görsel/link BURADAN değil, slug üzerinden canlı
// projects tablosundan her istekte taze çekilir (bkz. kullanıcı isteği: "proje ismini düzenle
// ekranından değişince burada da otomatik değişsin") — admin bir projeyi yeniden adlandırırsa
// bu dosyaya DOKUNMADAN otomatik yansır. slug: null olan kayıtlar sitede henüz ayrı bir proje
// kaydı olarak bulunamadı (bkz. kullanıcı isteği: "linki verilmemiş projeleri tespit et" — bu
// geçişte 1335 canlı proje başlığına karşı eşleştirildi, geri kalanı için güvenilir bir eşleşme
// yok), düz metin olarak kalır; ileride bir proje eklenirse slug alanı elle doldurulabilir.
export const TOP100_BASELINE = [
  { rank: 1, name: "Ayasofya", slug: "ayasofya-camii", baseAvg: 4.95, baseCount: 200 },
  { rank: 2, name: "Selimiye Camii", slug: "selimiye-camii", baseAvg: 4.89, baseCount: 185 },
  { rank: 3, name: "Divriği Ulu Camii", slug: "divrigi-ulu-camii", baseAvg: 4.88, baseCount: 182 },
  { rank: 4, name: "Süleymaniye Camii", slug: "suleymaniye-camii", baseAvg: 4.87, baseCount: 179 },
  { rank: 5, name: "Aspendos", slug: "aspendos", baseAvg: 4.86, baseCount: 176 },
  { rank: 6, name: "Göbeklitepe", slug: "gobeklitepe", baseAvg: 4.85, baseCount: 174 },
  { rank: 7, name: "Atatürk Kültür Merkezi", slug: "ataturk-kultur-merkezi", baseAvg: 4.84, baseCount: 172 },
  { rank: 8, name: "Topkapı Sarayı", slug: "topkapi-sarayi", baseAvg: 4.83, baseCount: 170 },
  { rank: 9, name: "Anıtkabir", slug: "anitkabir", baseAvg: 4.83, baseCount: 167 },
  { rank: 10, name: "Florya Atatürk Köşkü", slug: "florya-ataturk-deniz-kosku", baseAvg: 4.82, baseCount: 165 },
  { rank: 11, name: "ODTÜ Mimarlık Fakültesi", slug: "odtu-mimarlik-fakultesi", baseAvg: 4.81, baseCount: 163 },
  { rank: 12, name: "Sümela Manastırı", slug: "sumela-manastiri", baseAvg: 4.8, baseCount: 161 },
  { rank: 13, name: "Türk Tarih Kurumu", slug: "turk-tarih-kurumu", baseAvg: 4.79, baseCount: 159 },
  { rank: 14, name: "Haydarpaşa", slug: "haydarpasa-gari", baseAvg: 4.79, baseCount: 157 },
  { rank: 15, name: "Celsus Kitaplığı", slug: "celsus-kutuphanesi", baseAvg: 4.78, baseCount: 155 },
  { rank: 16, name: "Amcazade Yalısı", slug: "amcazade-yalisi", baseAvg: 4.77, baseCount: 153 },
  { rank: 17, name: "İstanbul Manifaturacılar Çarşısı (İMÇ)", slug: "istanbul-manifaturacilar-carsisi-imc", baseAvg: 4.77, baseCount: 152 },
  { rank: 18, name: "İshak Paşa Sarayı", slug: "ishak-pasa-sarayi", baseAvg: 4.76, baseCount: 150 },
  { rank: 19, name: "TBMM Camii", slug: "tbmm-camii", baseAvg: 4.75, baseCount: 148 },
  { rank: 20, name: "Rüstem Paşa Camii", slug: "rustem-pasa-camii", baseAvg: 4.75, baseCount: 146 },
  { rank: 21, name: "SSK Zeyrek Tesisleri", slug: "sosyal-sigortalar-kompleksi", baseAvg: 4.74, baseCount: 144 },
  { rank: 22, name: "Kapalıçarşı", slug: "kapalicarsi", baseAvg: 4.73, baseCount: 142 },
  { rank: 23, name: "Sokullu Mehmet Paşa Camii", slug: "sokullu-mehmed-pasa-camii-kadirga", baseAvg: 4.73, baseCount: 140 },
  { rank: 24, name: "Yerebatan Sarnıcı", slug: "yerebatan-sarnici-basilica-cistern", baseAvg: 4.72, baseCount: 139 },
  { rank: 25, name: "Botter Apartmanı", slug: "botter-apartmani", baseAvg: 4.71, baseCount: 137 },
  { rank: 26, name: "Çatalhöyük", slug: "catalhoyuk", baseAvg: 4.71, baseCount: 135 },
  { rank: 27, name: "Şemsi Paşa Camii", slug: "semsi-pasa-camii", baseAvg: 4.7, baseCount: 133 },
  { rank: 28, name: "Bursa Ulu Camii", slug: null, baseAvg: 4.69, baseCount: 132 },
  { rank: 29, name: "Dolmabahçe Sarayı", slug: "dolmabahce-sarayi", baseAvg: 4.69, baseCount: 130 },
  { rank: 30, name: "Galata Kulesi", slug: "galata-kulesi", baseAvg: 4.68, baseCount: 128 },
  { rank: 31, name: "Ankara Dil, Tarih, Coğrafya Fakültesi", slug: null, baseAvg: 4.67, baseCount: 126 },
  { rank: 32, name: "Büyük Postane", slug: "buyuk-postane", baseAvg: 4.67, baseCount: 125 },
  { rank: 33, name: "Kariye", slug: "kariye-camii", baseAvg: 4.66, baseCount: 123 },
  { rank: 34, name: "Mağlova Su Kemeri", slug: "maglova-kemeri", baseAvg: 4.65, baseCount: 121 },
  { rank: 35, name: "Milli Reasürans Çarşısı", slug: "milli-reasurans-genel-mudurlugu-binasi", baseAvg: 4.65, baseCount: 120 },
  { rank: 36, name: "ODTÜ Kampüsü", slug: null, baseAvg: 4.64, baseCount: 118 },
  { rank: 37, name: "Edirne II. Beyazıt Külliyesi", slug: null, baseAvg: 4.64, baseCount: 116 },
  { rank: 38, name: "Bodrum Demir Evleri", slug: null, baseAvg: 4.63, baseCount: 115 },
  { rank: 39, name: "Beyşehir Eşrefoğlu Camii", slug: null, baseAvg: 4.62, baseCount: 113 },
  { rank: 40, name: "Karatepe Kazı Alanı Saçakları", slug: "karatepe-aslantas-acik-hava-muzesi", baseAvg: 4.62, baseCount: 111 },
  { rank: 41, name: "Osmanlı Bankası Müzesi (Salt Galata)", slug: null, baseAvg: 4.61, baseCount: 110 },
  { rank: 42, name: "Süleymaniye Külliyesi", slug: "suleymaniye-camii", baseAvg: 4.61, baseCount: 108 },
  { rank: 43, name: "İstanbul Surları", slug: null, baseAvg: 4.6, baseCount: 106 },
  { rank: 44, name: "Didim Apollon Tapınağı", slug: "didyma-apollon-tapinagi", baseAvg: 4.59, baseCount: 105 },
  { rank: 45, name: "Mihrimah Sultan Camii", slug: null, baseAvg: 4.59, baseCount: 103 },
  { rank: 46, name: "Taut Evi", slug: null, baseAvg: 4.58, baseCount: 101 },
  { rank: 47, name: "Türk Dil Kurumu Binası", slug: "turk-dil-kurumu", baseAvg: 4.58, baseCount: 100 },
  { rank: 48, name: "Diyarbakır Kalesi, Surları ve Hevsel Bahçeleri", slug: null, baseAvg: 4.57, baseCount: 98 },
  { rank: 49, name: "Sancaklar Camii", slug: "sancaklar-camii", baseAvg: 4.56, baseCount: 97 },
  { rank: 50, name: "Akdamar Kilisesi", slug: "akdamar-kilisesi", baseAvg: 4.56, baseCount: 95 },
  { rank: 51, name: "Bursa Yeşil Camii", slug: null, baseAvg: 4.55, baseCount: 93 },
  { rank: 52, name: "Efes Antik Kenti", slug: null, baseAvg: 4.55, baseCount: 92 },
  { rank: 53, name: "Büyükada Anadolu Kulübü", slug: "buyukada-anadolu-kulubu", baseAvg: 4.54, baseCount: 90 },
  { rank: 54, name: "İstanbul Üniversitesi Fen, Edebiyat Fakültesi", slug: null, baseAvg: 4.53, baseCount: 89 },
  { rank: 55, name: "Ani Harabeleri", slug: "ani-harabeleri", baseAvg: 4.53, baseCount: 87 },
  { rank: 56, name: "Erzurum Çifte Minare", slug: null, baseAvg: 4.52, baseCount: 86 },
  { rank: 57, name: "TBMM", slug: null, baseAvg: 4.52, baseCount: 84 },
  { rank: 58, name: "Ankara Garı ve Gazinosu", slug: null, baseAvg: 4.51, baseCount: 82 },
  { rank: 59, name: "İstanbul Bilgi Üniversitesi Santral Kampüsü", slug: null, baseAvg: 4.51, baseCount: 81 },
  { rank: 60, name: "Büyükada Rum Yetimhanesi", slug: null, baseAvg: 4.5, baseCount: 79 },
  { rank: 61, name: "Sultanhanı Kervansarayı", slug: null, baseAvg: 4.49, baseCount: 78 },
  { rank: 62, name: "Artemis Tapınağı", slug: null, baseAvg: 4.49, baseCount: 76 },
  { rank: 63, name: "Şeyh Zafirin Türbesi ve Kitaplığı", slug: null, baseAvg: 4.48, baseCount: 75 },
  { rank: 64, name: "Afrodisyas Antik Kenti", slug: null, baseAvg: 4.48, baseCount: 73 },
  { rank: 65, name: "Ahlat Selçuklu Mezarlığı", slug: null, baseAvg: 4.47, baseCount: 72 },
  { rank: 66, name: "Bergama Açıkhava Tiyatrosu", slug: null, baseAvg: 4.47, baseCount: 70 },
  { rank: 67, name: "Taşkışla", slug: "taskisla", baseAvg: 4.46, baseCount: 69 },
  { rank: 68, name: "İş Bankası Eski Genel Müdürlük Binası", slug: null, baseAvg: 4.45, baseCount: 67 },
  { rank: 69, name: "Nemrud Dağı Antiochus Anıt Mezarı", slug: null, baseAvg: 4.45, baseCount: 66 },
  { rank: 70, name: "Sergios Bakhos (Küçük Ayasofya)", slug: "kucuk-ayasofya-camii", baseAvg: 4.44, baseCount: 64 },
  { rank: 71, name: "Deyrülzafaran Manastırı", slug: "deyrulzafaran-manastiri", baseAvg: 4.44, baseCount: 63 },
  { rank: 72, name: "Sagalassos", slug: "sagalassos-antik-kenti", baseAvg: 4.43, baseCount: 61 },
  { rank: 73, name: "Mimar Vedat Tek Evi", slug: null, baseAvg: 4.43, baseCount: 60 },
  { rank: 74, name: "Rumelihisarı", slug: "rumeli-hisari", baseAvg: 4.42, baseCount: 58 },
  { rank: 75, name: "Hattuşa", slug: "hattusa-bogazkoy-antik-kenti", baseAvg: 4.42, baseCount: 57 },
  { rank: 76, name: "Hukukçular Sitesi", slug: null, baseAvg: 4.41, baseCount: 55 },
  { rank: 77, name: "Ankara Sergi Evi", slug: null, baseAvg: 4.4, baseCount: 54 },
  { rank: 78, name: "Birgi Çakırağa Konağı", slug: null, baseAvg: 4.4, baseCount: 52 },
  { rank: 79, name: "Priene Apollon Tapınağı", slug: null, baseAvg: 4.39, baseCount: 51 },
  { rank: 80, name: "Ortaköy Camii", slug: "ortakoy-camii", baseAvg: 4.39, baseCount: 49 },
  { rank: 81, name: "Ayvacık B2 Evi", slug: "b2-evi", baseAvg: 4.38, baseCount: 48 },
  { rank: 82, name: "Bergama Antik Kenti", slug: null, baseAvg: 4.38, baseCount: 46 },
  { rank: 83, name: "Harran Kubbeli Evleri", slug: null, baseAvg: 4.37, baseCount: 45 },
  { rank: 84, name: "Fener Rum Patrikhanesi / Lisesi / Balat Rum Okulu", slug: null, baseAvg: 4.37, baseCount: 43 },
  { rank: 85, name: "İstanbul Hilton Oteli", slug: null, baseAvg: 4.36, baseCount: 42 },
  { rank: 86, name: "Amanruya Otel", slug: "amanruya-oteli", baseAvg: 4.35, baseCount: 40 },
  { rank: 87, name: "Bergama Zeus Altarı", slug: null, baseAvg: 4.35, baseCount: 39 },
  { rank: 88, name: "Şehzade Camii", slug: "sehzade-camii", baseAvg: 4.34, baseCount: 37 },
  { rank: 89, name: "Safranbolu Evleri", slug: null, baseAvg: 4.34, baseCount: 36 },
  { rank: 90, name: "Kızkulesi", slug: "kiz-kulesi", baseAvg: 4.33, baseCount: 34 },
  { rank: 91, name: "Nuruosmaniye", slug: "nuruosmaniye-camii", baseAvg: 4.33, baseCount: 33 },
  { rank: 92, name: "Sultanahmet Camii ve Külliyesi", slug: "sultanahmet-camii", baseAvg: 4.32, baseCount: 32 },
  { rank: 93, name: "Cumhurbaşkanlığı Köşkü", slug: null, baseAvg: 4.32, baseCount: 30 },
  { rank: 94, name: "Aya İrini", slug: "aya-irini-kilisesi", baseAvg: 4.31, baseCount: 29 },
  { rank: 95, name: "Bodrum Ahmet Ertegün Evi", slug: "ertegun-evi-2", baseAvg: 4.31, baseCount: 27 },
  { rank: 96, name: "Priene Antik Kenti", slug: "priene-antik-kenti", baseAvg: 4.3, baseCount: 26 },
  { rank: 97, name: "Çerkezköy ATK Lojmanları", slug: null, baseAvg: 4.3, baseCount: 24 },
  { rank: 98, name: "Kılıç Ali Paşa Camii", slug: "kilic-ali-pasa-camii", baseAvg: 4.29, baseCount: 23 },
  { rank: 99, name: "Rıza Derviş Villası", slug: null, baseAvg: 4.29, baseCount: 21 },
  { rank: 100, name: "Üsküdar Şemsi Paşa Külliyesi", slug: "semsi-pasa-camii", baseAvg: 4.28, baseCount: 20 },
];
