// Türkiye'deki üniversitelerin adları (YÖK listesi) — sitedeki TÜM "Üniversite" kutularının öneri
// kaynağı (kullanıcı isteği, 2026-09-01: kişi ekle/düzenle, ardından "Üye Ol ve Hesabım'daki
// üniversite kutularına da ekle").
//
// TEK KULLANICI: src/routes/architect.js#handleArchitectSchoolsRoute. Liste D1'e KONULMADI çünkü
// hiçbir sorgu okula göre JOIN/filtre yapmıyor — alan yalnızca serbest metin olarak saklanıp
// gösteriliyor; bir migration + yönetim ekranı, nadiren değişen sabit bir referans listesi için
// gereksiz olurdu.
//
// NEDEN ROUTE'TAN SERVİS EDİLİYOR, İSTEMCİDE STATİK BİR .js DEĞİL: aynı kutu ÜÇ ayrı yerde var
// (kisi-ekle.html, uye-ol.html, js/components/auth-modal.js'in HEM Üye Ol HEM Profili Düzenle
// formu) ve auth-modal.js site genelinde yükleniyor. Statik bir <script> her sayfaya eklenmek
// zorunda kalırdı; /api/architects/schools ise üçünün de ZATEN çağırdığı tek uç.
//
// Uç, bu listeyi architects.school'daki GERÇEK değerlerle birleştirir — yurt dışı üniversiteleri ve
// buraya henüz eklenmemiş yeni kurumlar önerilmeye devam eder. Yeni bir üniversite kurulduğunda
// yalnızca buraya eklenmesi yeterlidir.
export const TR_UNIVERSITIES = [

  // ---- Devlet üniversiteleri ----
  'Abdullah Gül Üniversitesi',
  'Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi',
  'Adıyaman Üniversitesi',
  'Afyon Kocatepe Üniversitesi',
  'Afyonkarahisar Sağlık Bilimleri Üniversitesi',
  'Ağrı İbrahim Çeçen Üniversitesi',
  'Akdeniz Üniversitesi',
  'Aksaray Üniversitesi',
  'Alanya Alaaddin Keykubat Üniversitesi',
  'Amasya Üniversitesi',
  'Anadolu Üniversitesi',
  'Ankara Üniversitesi',
  'Ankara Hacı Bayram Veli Üniversitesi',
  'Ankara Müzik ve Güzel Sanatlar Üniversitesi',
  'Ankara Sosyal Bilimler Üniversitesi',
  'Ankara Yıldırım Beyazıt Üniversitesi',
  'Ardahan Üniversitesi',
  'Artvin Çoruh Üniversitesi',
  'Atatürk Üniversitesi',
  'Aydın Adnan Menderes Üniversitesi',
  'Balıkesir Üniversitesi',
  'Bandırma Onyedi Eylül Üniversitesi',
  'Bartın Üniversitesi',
  'Batman Üniversitesi',
  'Bayburt Üniversitesi',
  'Bilecik Şeyh Edebali Üniversitesi',
  'Bingöl Üniversitesi',
  'Bitlis Eren Üniversitesi',
  'Boğaziçi Üniversitesi',
  'Bolu Abant İzzet Baysal Üniversitesi',
  'Burdur Mehmet Akif Ersoy Üniversitesi',
  'Bursa Teknik Üniversitesi',
  'Bursa Uludağ Üniversitesi',
  'Çanakkale Onsekiz Mart Üniversitesi',
  'Çankırı Karatekin Üniversitesi',
  'Çukurova Üniversitesi',
  'Dicle Üniversitesi',
  'Dokuz Eylül Üniversitesi',
  'Düzce Üniversitesi',
  'Ege Üniversitesi',
  'Erciyes Üniversitesi',
  'Erzincan Binali Yıldırım Üniversitesi',
  'Erzurum Teknik Üniversitesi',
  'Eskişehir Osmangazi Üniversitesi',
  'Eskişehir Teknik Üniversitesi',
  'Fırat Üniversitesi',
  'Galatasaray Üniversitesi',
  'Gazi Üniversitesi',
  'Gaziantep Üniversitesi',
  'Gaziantep İslam Bilim ve Teknoloji Üniversitesi',
  'Gebze Teknik Üniversitesi',
  'Giresun Üniversitesi',
  'Gümüşhane Üniversitesi',
  'Hacettepe Üniversitesi',
  'Hakkari Üniversitesi',
  'Harran Üniversitesi',
  'Hatay Mustafa Kemal Üniversitesi',
  'Hitit Üniversitesi',
  'Iğdır Üniversitesi',
  'Isparta Uygulamalı Bilimler Üniversitesi',
  'İnönü Üniversitesi',
  'İskenderun Teknik Üniversitesi',
  'İstanbul Üniversitesi',
  'İstanbul Üniversitesi-Cerrahpaşa',
  'İstanbul Medeniyet Üniversitesi',
  'İstanbul Teknik Üniversitesi',
  'İzmir Bakırçay Üniversitesi',
  'İzmir Demokrasi Üniversitesi',
  'İzmir Kâtip Çelebi Üniversitesi',
  'İzmir Yüksek Teknoloji Enstitüsü',
  'Jandarma ve Sahil Güvenlik Akademisi',
  'Kafkas Üniversitesi',
  'Kahramanmaraş İstiklal Üniversitesi',
  'Kahramanmaraş Sütçü İmam Üniversitesi',
  'Karabük Üniversitesi',
  'Karadeniz Teknik Üniversitesi',
  'Karamanoğlu Mehmetbey Üniversitesi',
  'Kastamonu Üniversitesi',
  'Kayseri Üniversitesi',
  'Kırıkkale Üniversitesi',
  'Kırklareli Üniversitesi',
  'Kırşehir Ahi Evran Üniversitesi',
  'Kilis 7 Aralık Üniversitesi',
  'Kocaeli Üniversitesi',
  'Konya Teknik Üniversitesi',
  'Kütahya Dumlupınar Üniversitesi',
  'Kütahya Sağlık Bilimleri Üniversitesi',
  'Malatya Turgut Özal Üniversitesi',
  'Manisa Celâl Bayar Üniversitesi',
  'Mardin Artuklu Üniversitesi',
  'Marmara Üniversitesi',
  'Mersin Üniversitesi',
  'Milli Savunma Üniversitesi',
  'Muğla Sıtkı Koçman Üniversitesi',
  'Munzur Üniversitesi',
  'Muş Alparslan Üniversitesi',
  'Necmettin Erbakan Üniversitesi',
  'Nevşehir Hacı Bektaş Veli Üniversitesi',
  'Niğde Ömer Halisdemir Üniversitesi',
  'Ondokuz Mayıs Üniversitesi',
  'Ordu Üniversitesi',
  'Orta Doğu Teknik Üniversitesi',
  'Osmaniye Korkut Ata Üniversitesi',
  'Pamukkale Üniversitesi',
  'Polis Akademisi',
  'Recep Tayyip Erdoğan Üniversitesi',
  'Sağlık Bilimleri Üniversitesi',
  'Sakarya Üniversitesi',
  'Sakarya Uygulamalı Bilimler Üniversitesi',
  'Samsun Üniversitesi',
  'Selçuk Üniversitesi',
  'Siirt Üniversitesi',
  'Sinop Üniversitesi',
  'Sivas Bilim ve Teknoloji Üniversitesi',
  'Sivas Cumhuriyet Üniversitesi',
  'Süleyman Demirel Üniversitesi',
  'Şırnak Üniversitesi',
  'Tarsus Üniversitesi',
  'Tekirdağ Namık Kemal Üniversitesi',
  'Tokat Gaziosmanpaşa Üniversitesi',
  'Trabzon Üniversitesi',
  'Trakya Üniversitesi',
  'Türk-Alman Üniversitesi',
  'Uşak Üniversitesi',
  'Van Yüzüncü Yıl Üniversitesi',
  'Yalova Üniversitesi',
  'Yıldız Teknik Üniversitesi',
  'Yozgat Bozok Üniversitesi',
  'Zonguldak Bülent Ecevit Üniversitesi',
  // ---- Vakıf üniversiteleri ----
  'Acıbadem Mehmet Ali Aydınlar Üniversitesi',
  'Alanya Hamdullah Emin Paşa Üniversitesi',
  'Ankara Bilim Üniversitesi',
  'Ankara Medipol Üniversitesi',
  'Antalya Belek Üniversitesi',
  'Atılım Üniversitesi',
  'Avrasya Üniversitesi',
  'Bahçeşehir Üniversitesi',
  'Başkent Üniversitesi',
  'Beykoz Üniversitesi',
  'Bezm-i Âlem Vakıf Üniversitesi',
  'Biruni Üniversitesi',
  'Çağ Üniversitesi',
  'Çankaya Üniversitesi',
  'Doğuş Üniversitesi',
  'Fatih Sultan Mehmet Vakıf Üniversitesi',
  'Fenerbahçe Üniversitesi',
  'Haliç Üniversitesi',
  'Hasan Kalyoncu Üniversitesi',
  'Işık Üniversitesi',
  'İbn Haldun Üniversitesi',
  'İhsan Doğramacı Bilkent Üniversitesi',
  'İstanbul 29 Mayıs Üniversitesi',
  'İstanbul Arel Üniversitesi',
  'İstanbul Atlas Üniversitesi',
  'İstanbul Aydın Üniversitesi',
  'İstanbul Beykent Üniversitesi',
  'İstanbul Bilgi Üniversitesi',
  'İstanbul Esenyurt Üniversitesi',
  'İstanbul Galata Üniversitesi',
  'İstanbul Gedik Üniversitesi',
  'İstanbul Gelişim Üniversitesi',
  'İstanbul Kent Üniversitesi',
  'İstanbul Kültür Üniversitesi',
  'İstanbul Medipol Üniversitesi',
  'İstanbul Nişantaşı Üniversitesi',
  'İstanbul Okan Üniversitesi',
  'İstanbul Rumeli Üniversitesi',
  'İstanbul Sabahattin Zaim Üniversitesi',
  'İstanbul Ticaret Üniversitesi',
  'İstanbul Topkapı Üniversitesi',
  'İstanbul Yeni Yüzyıl Üniversitesi',
  'İstinye Üniversitesi',
  'İzmir Ekonomi Üniversitesi',
  'İzmir Tınaztepe Üniversitesi',
  'Kadir Has Üniversitesi',
  'Kapadokya Üniversitesi',
  'Koç Üniversitesi',
  'Konya Gıda ve Tarım Üniversitesi',
  'KTO Karatay Üniversitesi',
  'Lokman Hekim Üniversitesi',
  'Maltepe Üniversitesi',
  'MEF Üniversitesi',
  'Nuh Naci Yazgan Üniversitesi',
  'Ostim Teknik Üniversitesi',
  'Özyeğin Üniversitesi',
  'Piri Reis Üniversitesi',
  'Sabancı Üniversitesi',
  'Sanko Üniversitesi',
  'TED Üniversitesi',
  'TOBB Ekonomi ve Teknoloji Üniversitesi',
  'Toros Üniversitesi',
  'Türk Hava Kurumu Üniversitesi',
  'Ufuk Üniversitesi',
  'Üsküdar Üniversitesi',
  'Yaşar Üniversitesi',
  'Yeditepe Üniversitesi',
  'Yüksek İhtisas Üniversitesi',
];
