// MİMARLAB — Haberler veri kaynağı
const newsItems = [
  {id:"uluslararasi-mimarlik-elestirmenleri-komitesinden-ankara-nin",title:"Uluslararası mimarlık eleştirmenleri komitesinden Ankara'nın kentleşme tarihine ödül", category:"Güncel", image:"projects/haber-cica-odul.jpg"},
  {id:"turk-ogrenciler-saint-gobain-in-uluslararasi-ogrenci-yarisma",title:"Türk öğrenciler Saint-Gobain'in uluslararası öğrenci yarışmasında Türkiye'yi temsil etti", category:"Yarışma", image:"projects/haber-saintgobain-yarisma.jpg"},
  {id:"modern-mimarlik-arastirmalari-destek-programi-2026-sonuclari",title:"Modern Mimarlık Araştırmaları Destek Programı 2026 sonuçları açıklandı", category:"Güncel", image:"projects/haber-modern-arastirma-destek.jpg"},
  {id:"kampusaktif-ogrenci-tasarim-yarismasi-odul-torenini-gercekle",title:"KampüsAktif Öğrenci Tasarım Yarışması ödül törenini gerçekleştirdi", category:"Yarışma", image:"projects/haber-kampusaktif-yarisma.jpg"},
  {id:"ulusal-mimarlik-sergisi-nde-mimar-sinan-buyuk-odulu-sahipler",title:"Ulusal Mimarlık Sergisi'nde Mimar Sinan Büyük Ödülü sahiplerini buldu", category:"Etkinlik", image:"projects/haber-ulusal-mimarlik-sergisi.jpg"},
  {id:"mugla-buyuksehir-belediyesi-hizmet-binasi-icin-mimari-proje-",title:"Muğla Büyükşehir Belediyesi hizmet binası için mimari proje yarışması açtı", category:"Yarışma", image:"projects/haber-mugla-yarisma.jpg"},
  {id:"trabzon-buyuksehir-belediyesi-kultur-ve-sanat-merkezi-icin-u",title:"Trabzon Büyükşehir Belediyesi Kültür ve Sanat Merkezi için ulusal yarışma başlattı", category:"Yarışma", image:"projects/haber-trabzon-yarisma.jpg"},
  {id:"tab-2026-enstalasyon-yarismasi-kazanani-bienal-acilis-haftas",title:"TAB 2026 enstalasyon yarışması kazananı bienal açılış haftasında inşa edilecek", category:"Etkinlik", image:"projects/haber-tab2026-enstalasyon.jpg"},

  {id:"mimarlar-odasi-ulusal-mimarlik-odulleri-nde-bu-yilki-basvuru",title:"Mimarlar Odası Ulusal Mimarlık Ödülleri'nde bu yılki başvuru süreci başladı", category:"Ödül", image:"projects/haber-placeholder/odul.svg"},
  {id:"bursa-buyuksehir-belediyesi-kent-meydani-icin-iki-asamali-fi",title:"Bursa Büyükşehir Belediyesi kent meydanı için iki aşamalı fikir yarışması açtı", category:"Yarışma", image:"projects/haber-placeholder/yarisma.svg"},
  {id:"yapi-endustri-merkezi-nin-yillik-surdurulebilir-yapi-oduller",title:"Yapı-Endüstri Merkezi'nin yıllık sürdürülebilir yapı ödülleri sahiplerini buldu", category:"Ödül", image:"projects/haber-placeholder/odul.svg"},
  {id:"istanbul-da-bir-sanayi-mirasi-yapisinin-restorasyon-sureci-t",title:"İstanbul'da bir sanayi mirası yapısının restorasyon süreci tamamlandı", category:"Restorasyon", image:"projects/haber-placeholder/restorasyon.svg"},
  {id:"genc-mimarlar-icin-duzenlenen-paviyon-tasarim-yarismasina-ba",title:"Genç mimarlar için düzenlenen paviyon tasarım yarışmasına başvurular açıldı", category:"Yarışma", image:"projects/haber-placeholder/yarisma.svg"},
  {id:"turkiye-den-bir-ekip-avrupa-birligi-kentsel-tasarim-yarismas",title:"Türkiye'den bir ekip, Avrupa Birliği kentsel tasarım yarışmasında finale kaldı", category:"Yarışma", image:"projects/haber-placeholder/yarisma.svg"},
  {id:"mimarlik-fakulteleri-arasi-bitirme-projeleri-sergisi-bu-ay-a",title:"Mimarlık fakülteleri arası bitirme projeleri sergisi bu ay açılıyor", category:"Sergi", image:"projects/haber-placeholder/sergi.svg"},
  {id:"ahsap-yapi-teknikleri-uzerine-duzenlenen-atolye-calismasi-bu",title:"Ahşap yapı teknikleri üzerine düzenlenen atölye çalışması büyük ilgi gördü", category:"Etkinlik", image:"projects/haber-placeholder/etkinlik.svg"},
  {id:"izmir-de-tarihi-bir-carsi-yapisi-ozgun-dokusu-korunarak-yeni",title:"İzmir'de tarihi bir çarşı yapısı özgün dokusu korunarak yeniden işlevlendirildi", category:"Restorasyon", image:"projects/haber-placeholder/restorasyon.svg"},
  {id:"sifir-karbon-hedefli-bir-ofis-binasi-projesi-uluslararasi-ba",title:"Sıfır karbon hedefli bir ofis binası projesi uluslararası basında yer aldı", category:"Sürdürülebilirlik", image:"projects/haber-placeholder/surdurulebilirlik.svg"},
  {id:"bir-vakif-universitesi-kampus-yenileme-calismasi-icin-mimari",title:"Bir vakıf üniversitesi, kampüs yenileme çalışması için mimari yarışma başlattı", category:"Yarışma", image:"projects/haber-placeholder/yarisma.svg"},
  {id:"deprem-sonrasi-yeniden-yapilanma-uzerine-duzenlenen-sempozyu",title:"Deprem sonrası yeniden yapılanma üzerine düzenlenen sempozyum sona erdi", category:"Akademik", image:"projects/haber-placeholder/akademik.svg"},
  {id:"bir-belediye-kentsel-donusum-alani-icin-katilimci-tasarim-su",title:"Bir belediye, kentsel dönüşüm alanı için katılımcı tasarım sürecini başlattı", category:"Güncel", image:"projects/haber-placeholder/guncel.svg"},
  {id:"peyzaj-mimarligi-ogrencilerinin-kentsel-yesil-alan-onerileri",title:"Peyzaj mimarlığı öğrencilerinin kentsel yeşil alan önerileri sergilendi", category:"Sergi", image:"projects/haber-placeholder/sergi.svg"},
  {id:"ankara-da-bir-muze-binasi-icin-duzenlenen-mimari-proje-yaris",title:"Ankara'da bir müze binası için düzenlenen mimari proje yarışması sonuçlandı", category:"Yarışma", image:"projects/haber-placeholder/yarisma.svg"},
  {id:"geleneksel-yapi-malzemeleri-uzerine-hazirlanan-arastirma-rap",title:"Geleneksel yapı malzemeleri üzerine hazırlanan araştırma raporu yayımlandı", category:"Akademik", image:"projects/haber-placeholder/akademik.svg"},
  {id:"bir-mimarlik-ofisi-gunes-enerjisiyle-calisan-konut-projesiyl",title:"Bir mimarlık ofisi, güneş enerjisiyle çalışan konut projesiyle ödül kazandı", category:"Ödül", image:"projects/haber-placeholder/odul.svg"},
  {id:"kadikoy-de-bir-eski-fabrika-binasi-kultur-merkezine-donustur",title:"Kadıköy'de bir eski fabrika binası kültür merkezine dönüştürülmek üzere ihaleye çıktı", category:"Güncel", image:"projects/haber-placeholder/guncel.svg"},
  {id:"uluslararasi-bir-mimarlik-bienaline-turkiye-den-davet-edilen",title:"Uluslararası bir mimarlık bienaline Türkiye'den davet edilen ekip belli oldu", category:"Etkinlik", image:"projects/haber-placeholder/etkinlik.svg"},
  {id:"tarihi-bir-hamam-yapisinin-rolove-ve-restorasyon-projesi-tam",title:"Tarihi bir hamam yapısının rölöve ve restorasyon projesi tamamlandı", category:"Restorasyon", image:"projects/haber-placeholder/restorasyon.svg"},
  {id:"ogrenci-topluluklarinin-duzenledigi-maket-yarismasinda-derec",title:"Öğrenci topluluklarının düzenlediği maket yarışmasında dereceye girenler açıklandı", category:"Yarışma", image:"projects/haber-placeholder/yarisma.svg"},
  {id:"bir-sehir-tarihi-merkezinin-yaya-bolgesi-projesi-icin-tasari",title:"Bir şehir, tarihi merkezinin yaya bölgesi projesi için tasarım yarışması açtı", category:"Yarışma", image:"projects/haber-placeholder/yarisma.svg"},
  {id:"mimarlikta-dijitallesme-ve-yapay-zek-konulu-panel-genis-kati",title:"Mimarlıkta dijitalleşme ve yapay zekâ konulu panel geniş katılımla gerçekleşti", category:"Etkinlik", image:"projects/haber-placeholder/etkinlik.svg"},
  {id:"bir-belediyenin-kent-parki-projesi-uluslararasi-peyzaj-odulu",title:"Bir belediyenin kent parkı projesi uluslararası peyzaj ödülüne aday gösterildi", category:"Ödül", image:"projects/haber-placeholder/odul.svg"},
  {id:"genc-mimarlar-bulusmasi-bu-yil-kirsal-mimarlik-temasiyla-duz",title:"Genç mimarlar buluşması bu yıl kırsal mimarlık temasıyla düzenlendi", category:"Etkinlik", image:"projects/haber-placeholder/etkinlik.svg"},
  {id:"bir-universitenin-mimarlik-bolumu-geri-donusturulmus-malzeme",title:"Bir üniversitenin mimarlık bölümü, geri dönüştürülmüş malzemeyle pavyon inşa etti", category:"Sürdürülebilirlik", image:"projects/haber-placeholder/surdurulebilirlik.svg"},
  {id:"restorasyon-meslek-orgutlerinden-tarihi-ahsap-yapi-stoku-ici",title:"Restorasyon meslek örgütlerinden tarihi ahşap yapı stoku için koruma çağrısı", category:"Güncel", image:"projects/haber-placeholder/guncel.svg"},
  {id:"bir-sahil-kasabasinda-iskele-ve-meydan-duzenlemesi-icin-tasa",title:"Bir sahil kasabasında iskele ve meydan düzenlemesi için tasarım yarışması açıldı", category:"Yarışma", image:"projects/haber-placeholder/yarisma.svg"},
  {id:"mimarlik-ogrencilerinin-kentsel-tasarim-studyosu-calismalari",title:"Mimarlık öğrencilerinin kentsel tasarım stüdyosu çalışmaları sergiye dönüştü", category:"Sergi", image:"projects/haber-placeholder/sergi.svg"},
  {id:"bir-kutuphane-projesi-uluslararasi-kamu-yapilari-odullerinde",title:"Bir kütüphane projesi, uluslararası kamu yapıları ödüllerinde kısa listeye kaldı", category:"Ödül", image:"projects/haber-placeholder/odul.svg"},
];

// Tarayıcıda `module` global'i tanımsız olduğu için bu blok yalnızca Worker'ın esbuild bundle'ında
// (nodejs_compat) çalışır — src/lib/seo.js buradan CJS interop ile import eder.
if (typeof module !== 'undefined') { module.exports = { newsItems }; }
